# docker-compose.yml

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  authentication:
    build:
      context: .
      dockerfile: authentication/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./authentication:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=authentication.config.settings

  sessions:
    build:
      context: .
      dockerfile: sessions/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./sessions:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=sessions.config.settings

  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - ./accounts:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=accounts.config.settings

volumes:
  postgres_data:
